[package]
name = "LocalLevelModel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
num-traits = "0.2"
csv = "1.1"
plotters = "0.3"
fast-float = "0.2"
